using System.Linq;
using System.Text.Json;
using System.Text.Json.Serialization;
using OldenEra.Generator.Models;
using OldenEra.Generator.Models.Unfrozen;
using OldenEra.Generator.Services;

namespace OldenEra.Generator.Tests;

/// <summary>
/// T-504 — User-editable RmgTemplate.description and displayWinCondition.
/// Empty override = generator's auto-generated value (byte-identical default).
/// Non-empty override = emitted verbatim.
/// </summary>
public class DescriptionDisplayWinConditionTests
{
    private static readonly JsonSerializerOptions EmitJsonOptions = new()
    {
        WriteIndented = false,
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
    };

    private static GeneratorSettings BaseSettings(MapTopology topology = MapTopology.Random) => new()
    {
        TemplateName = "T-504 Test",
        PlayerCount = 4,
        MapSize = 160,
        Topology = topology,
        Seed = 42,
    };

    [Fact]
    public void Default_NoOverride_DescriptionIsAutoGenerated()
    {
        var settings = BaseSettings();
        var template = TemplateGenerator.Generate(settings);

        Assert.False(string.IsNullOrEmpty(template.Description));
        // The auto-builder always begins with the topology label phrase.
        Assert.Contains("layout", template.Description!);
    }

    [Fact]
    public void Default_NoOverride_DisplayWinConditionEqualsVictoryCondition()
    {
        var settings = BaseSettings();
        settings.GameEndConditions.VictoryCondition = "win_condition_5";
        var template = TemplateGenerator.Generate(settings);

        Assert.Equal("win_condition_5", template.DisplayWinCondition);
    }

    [Fact]
    public void DescriptionOverride_EmitsVerbatim()
    {
        const string custom = "Hand-authored description.\nMulti-line\twith \"quotes\".";
        var settings = BaseSettings();
        settings.Description = custom;
        var template = TemplateGenerator.Generate(settings);

        Assert.Equal(custom, template.Description);
    }

    [Fact]
    public void DisplayWinConditionOverride_EmitsVerbatim()
    {
        const string custom = "Custom human-readable win cond.";
        var settings = BaseSettings();
        settings.DisplayWinCondition = custom;
        var template = TemplateGenerator.Generate(settings);

        Assert.Equal(custom, template.DisplayWinCondition);
    }

    [Fact]
    public void EmptyOverride_FallsBackToAutoGenerated()
    {
        var settings = BaseSettings();
        settings.Description = "";
        settings.DisplayWinCondition = "";
        settings.GameEndConditions.VictoryCondition = "win_condition_3";
        var template = TemplateGenerator.Generate(settings);

        Assert.Contains("layout", template.Description!);
        Assert.Equal("win_condition_3", template.DisplayWinCondition);
    }

    [Fact]
    public void DefaultOverrides_ProduceByteIdenticalOutput_AcrossAllPresets()
    {
        // Primary acceptance gate: a fresh GeneratorSettings (Description = "",
        // DisplayWinCondition = "") must produce the same JSON as before the
        // override fields existed for every shipped preset.
        var catalog = new PresetCatalog();
        Assert.NotEmpty(catalog.Entries);

        foreach (var entry in catalog.Entries)
        {
            var file = catalog.Load(entry.Id);
            var (s1, _, _, _) = SettingsMapper.FromFile(file);
            var (s2, _, _, _) = SettingsMapper.FromFile(file);
            // Pin the seed so any topology / layout RNG is deterministic.
            s1.Seed = 42;
            s2.Seed = 42;

            // s1: leave overrides at their default ("").
            // s2: explicitly clear (also "") — both must emit identically.
            s2.Description = "";
            s2.DisplayWinCondition = "";

            string j1 = JsonSerializer.Serialize(TemplateGenerator.Generate(s1), EmitJsonOptions);
            string j2 = JsonSerializer.Serialize(TemplateGenerator.Generate(s2), EmitJsonOptions);

            Assert.Equal(j1, j2);
        }
    }

    [Fact]
    public void SettingsFile_RoundTripsOverrides_ThroughMapper()
    {
        var g = BaseSettings();
        g.Description = "My custom description";
        g.DisplayWinCondition = "Win this way";

        var file = SettingsMapper.ToFile(g, advancedMode: false, experimentalMapSizes: false);
        Assert.Equal("My custom description", file.DescriptionOverride);
        Assert.Equal("Win this way", file.DisplayWinConditionOverride);

        var (back, _, _, _) = SettingsMapper.FromFile(file);
        Assert.Equal("My custom description", back.Description);
        Assert.Equal("Win this way", back.DisplayWinCondition);
    }

    [Fact]
    public void SettingsFile_RoundTripsOverrides_EmptyByDefault()
    {
        var g = BaseSettings();

        var file = SettingsMapper.ToFile(g, advancedMode: false, experimentalMapSizes: false);
        Assert.Equal("", file.DescriptionOverride);
        Assert.Equal("", file.DisplayWinConditionOverride);

        var (back, _, _, _) = SettingsMapper.FromFile(file);
        Assert.Equal("", back.Description);
        Assert.Equal("", back.DisplayWinCondition);
    }

    [Fact]
    public void SettingsFile_RoundTripsOverrides_ThroughShareCodec()
    {
        var g = BaseSettings();
        g.Description = "Multi\nline\noverride";
        g.DisplayWinCondition = "Custom WC label";

        var file = SettingsMapper.ToFile(g, advancedMode: false, experimentalMapSizes: false);
        string encoded = SettingsShareCodec.Encode(file);
        var decoded = SettingsShareCodec.TryDecode(encoded, out var status);

        Assert.Equal(SettingsShareCodec.DecodeStatus.Ok, status);
        Assert.NotNull(decoded);
        var (back, _, _, _) = SettingsMapper.FromFile(decoded!);

        Assert.Equal("Multi\nline\noverride", back.Description);
        Assert.Equal("Custom WC label", back.DisplayWinCondition);
    }
}
